#!/bin/sh

pushd $( dirname ${BASH_SOURCE:-$0} ) > /dev/null # go there the directory of this currently 'sourced' script ( quietly )

for c in core.d/*; do
    source $c
done

popd  > /dev/null # go back to working directory ( quietly )
