#!/bin/sh

pushd $( dirname ${BASH_SOURCE:-$0} ) > /dev/null # go there the directory of this currently 'sourced' script ( quietly )

source /etc/profile

source ./core

for s in profile.d/*; do
    source $s
done

popd  > /dev/null # go back to working directory ( quietly )
