#!/bin/sh


[ -z "$ENV" ] && export ENV="$HOME/.shell";
[ -z "$APP" ] && export OPT="$ENV/apps";
[ -z "$BIN" ] && export BIN="$ENV/bin";

[ -z "$PROJECTS" ] && export PROJECTS="$HOME/projects";

[ -z "$NPM_MODULES" ] && export NPM_MODULES=~/.npm-packages

export PATH=$BIN:$NPM_MODULES/bin:$PATH
