#!/bin/zsh

#
# This file should be sourced by ~/.zshrc (which runs AFTER ~/.zshenv)
pushd $( dirname ${BASH_SOURCE:-$0} ) > /dev/null # go there the directory of this currently 'sourced' script ( quietly )

source ../common/profile
source zsh-antigen
source zshenv
source zshrc


if [ -d $HOME/.profile.d/ ] && [ $(ls -A ~/.profile.d) ]; then
	for p in $HOME/.profile.d/*; do 
		source $p 
	done
fi

popd  > /dev/null # go back to working directory ( quietly )
