#!/bin/zsh

#
# This file should be sourced by ~/.zshrc (which runs AFTER ~/.zshenv)
#

pushd $( dirname ${BASH_SOURCE:-$0} ) > /dev/null # go there the directory of this currently 'sourced' script ( quietly )

source ../common/profile
source zshenv
source zshrc

popd  > /dev/null # go back to working directory ( quietly )
