#!/bin/zsh

export ANTIGEN_HOME=$HOME/.antigen
export ANTIGEN_CMD=$ANTIGEN_HOME/antigen.zsh

[ -d $ANTIGEN_HOME] || mkdir --parents $ANTIGEN_HOME
[ -e $ANTIGEN_CMD ] || (curl -L git.io/antigen > $ANTIGEN_CMD \
	&& echo "Antigen now installed $ANTIGEN_CMD")

source $ANTIGEN_CMD
