#!/bin/zsh

[[ -e "/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]] && source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
[[ -e "/usr/local/opt/findutils/libexec/gnubin" ]] && export PATH=/usr/local/opt/findutils/libexec/gnubin:$PATH

[[ -e  "/usr/libexec/java_home" ]] \
	&& export JAVA_HOME=$( /usr/libexec/java_home ) \
	&& export JRE_HOME=$JAVA_HOME/jre

if [[ -e "$HOME/.jenv" ]]; then
	export PATH="$HOME/.jenv/bin:$PATH"
	eval "$(jenv init -)"
	export JAVA_HOME=$( jenv javahome )
	export JRE_HOME=$JAVA_HOME/jre
	export MAVEN_OPTS="-XX:+UseG1GC -XX:MaxHeapFreeRatio=40"
fi

source /usr/local/share/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle pip
antigen bundle command-not-found
antigen bundle arialdomartini/oh-my-git

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
POWERLEVEL9K_INSTALLATION_PATH=$ANTIGEN_BUNDLES/bhilburn/powerlevel9k
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs vi_mode)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs history time)
antigen theme bhilburn/powerlevel9k powerlevel9k

#antigen theme robbyrussell

# Tell Antigen that you're done.
antigen apply

##############################################################################
# History Configuration
##############################################################################
HISTSIZE=5000               #How many lines of history to keep in memory
HISTFILE=~/.zsh_history     #Where to save history to disk
SAVEHIST=5000               #Number of history entries to save to disk
#HISTDUP=erase               #Erase duplicates in the history file
setopt    appendhistory     #Append history to the history file (no overwriting)
setopt    sharehistory      #Share history across terminals
setopt    incappendhistory  #Immediately append to the history file, not just when a term is killed

##############################################################################
# Fancy prompt config
##############################################################################

## zgitinit and prompt_wunjo_setup must be somewhere in your $fpath, see README for more.
## zgitinit handles gathering git information
## prompt_wunjo_setup is a prompt theme that makes use of the data collected by zgitinit
## https://github.com/jcorbin/zsh-git/tree
## http://www.wunjo.org/zsh-git/
#
#setopt promptsubst
#
## Load the prompt theme system
#autoload -U promptinit
#promptinit
#
## Use the wunjo prompt theme
#prompt wunjo
#
#
###############################################################################
## Completions
###############################################################################
#
## Matthew's setup of completion commands
#autoload -U compinit
#compinit
