#!/bin/zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Load bundles from the default repo (oh-my-zsh).
antigen bundle vi-mode
antigen bundle git
antigen bundle gitignore #https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/gitignore
antigen bundle pip
antigen bundle ng
antigen bundle command-not-found
antigen bundle python #https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/python
antigen bundle jenv #https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/jenv

# Load bundles from external repos.
antigen bundle arialdomartini/oh-my-git
antigen bundle jeffreytse/zsh-vi-mode
#antigen bundle softmoth/zsh-vim-mode
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
POWERLEVEL9K_INSTALLATION_PATH=$ANTIGEN_BUNDLES/bhilburn/powerlevel9k
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs vi_mode)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs history time)

case `uname` in
  Darwin)
	  POWERLEVEL9K_MODE='awesome-fontconfig'
  ;;
  Linux)
	  echo ""
  ;;
esac

antigen theme bhilburn/powerlevel9k powerlevel9k

#antigen theme robbyrussell

# Tell Antigen that you're done.
antigen apply

# Added by Quy 
stty intr \^X 
bindkey -M viins '^C' vi-cmd-mode

##############################################################################
# History Configuration
##############################################################################
HISTSIZE=5000               #How many lines of history to keep in memory
HISTFILE=~/.zsh_history     #Where to save history to disk
SAVEHIST=5000               #Number of history entries to save to disk
#HISTDUP=erase               #Erase duplicates in the history file
setopt    appendhistory     #Append history to the history file (no overwriting)
setopt    sharehistory      #Share history across terminals
setopt    incappendhistory  #Immediately append to the history file, not just when a term is killed

##############################################################################
# Fancy prompt config
##############################################################################

## zgitinit and prompt_wunjo_setup must be somewhere in your $fpath, see README for more.
## zgitinit handles gathering git information
## prompt_wunjo_setup is a prompt theme that makes use of the data collected by zgitinit
## https://github.com/jcorbin/zsh-git/tree
## http://www.wunjo.org/zsh-git/
#
#setopt promptsubst
#
## Load the prompt theme system
#autoload -U promptinit
#promptinit
#
## Use the wunjo prompt theme
#prompt wunjo
#
#
###############################################################################
## Completions
###############################################################################
#
## Matthew's setup of completion commands
#autoload -U compinit
#compinit
