#!/bin/sh

export REQUIRED_PACKAGES_INSTALLED="$HOME/.required-packages"
export STORE="$HOME/.store"
export APPSTORE="$STORE/apps"
export CACHESTORE="$STORE/cache"

#... Incase it's not already set (don't want to constraint the location)
[ -z "$DOTSHELL_ENV" ] && export DOTSHELL_ENV="$HOME/.shell"

export BIN="$DOTSHELL_ENV/bin"
export LOCAL="$DOTSHELL_ENV/local"
export LOCAL_BIN="$LOCAL/bin"
export APPS="$DOTSHELL_ENV/apps"
export CACHES="$DOTSHELL_ENV/config/caches"
export DOTFILES="$DOTSHELL_ENV/config/dotfiles"
export OVERLAYS="$DOTSHELL_ENV/config/overlays"
export OPT="$DOTSHELL_ENV/opt"
export STORELINK="$DOTSHELL_ENV/.store"
export REQUIRED_PACKAGES="$DOTSHELL_ENV/config/required/packages"
export REQUIRED_TAPS="$DOTSHELL_ENV/config/required/taps"
export REQUIRED_CASKS="$DOTSHELL_ENV/config/required/casks"

export PROJECTS="$HOME/projects"

export PATH="${LOCAL_BIN}:${BIN}:${PATH}"

[ -e "$BIN/cht.sh" ] || curl https://cht.sh/:cht.sh > "$BIN/cht.sh"
[ -x "$BIN/cht.sh" ] || chmod +x "$BIN/cht.sh"
