#!/bin/sh

export REQUIRED_PACKAGES_INSTALLED="$HOME/.required-packages"
export STORE="$HOME/.store"
export APPSTORE="$STORE/apps"
export CACHESTORE="$STORE/cache"

#... Incase it's not already set (don't want to constraint the location)
[ -z "$ENV" ] && export ENV="$HOME/.shell"

export BIN="$ENV/bin"
export LOCAL="$ENV/local"
export LOCAL_BIN="$LOCAL/bin"
export APPS="$ENV/apps"
export CACHES="$ENV/config/caches"
export DOTFILES="$ENV/config/dotfiles"
export OVERLAYS="$ENV/config/overlays"
export OPT="$ENV/opt"
export STORELINK="$ENV/.store"
export REQUIRED_PACKAGES="$ENV/config/required/packages"

export PROJECTS="$HOME/projects"
export NPM_PACKAGES="${HOME}/.npm-packages"

export PATH=$LOCAL_BIN:$BIN:$NPM_PACKAGES/bin:$PATH

