#!/bin/sh

function verboseExec() {
	local cmd="${1}"
	echo "${cmd}"
	eval "${cmd}"
}

function requireCmd() {
	local target=$1
	local description=${2:-$1}
	if [[ ! $(type -a $target) ]]; then
		echo "You need to install $description"
		exit 1
	fi
}

function ensureCmd() {
	local target="$1"
	local installCmd="$2"
	if [[ ! $(type -a $target) ]]; then
		verboseExec "${installCmd}"
	fi
}

function requireSource() {
	local target=$1
	local description=${2:-$1}
	[ -e $target ] || echo "You need to install $description" && return 1
}

function trySource() {
	local target=$1
	[ -e $target ] && source $target
}

function setOrInstall() {
	local name="$1"
	local path="$2"
	local installCmd=$3
	if [[ ! -e "$path" ]]; then
		verboseExec "${installCmd}"
	fi
	verboseExec "export ${name}=${path}"
}

function quid() {
	local size=${1:-4}
	cat /dev/urandom | tr -dc 'a-z0-9' | fold -w $size | head -n 1
}

function deepReadLink() {
	local target=$1

	cd $(dirname "$target")
	target=$(basename "$target")

	# Iterate down a (possible) chain of symlinks
	while [ -L "$target" ]
	do
	    target=$(readlink "$target")
	    cd $(dirname "$target")
	    target=$(basename "$target")
	done

	# Compute the canonicalized name by finding the physical path 
	# for the directory we're in and appending the target file.
	local path=`pwd -P`
	local result="$path/$target"

	echo $result
}


# Prints out the relative path between to absolute paths. Trivial.
#
# Parameters:
# $1 = first path
# $2 = second path
#
# Output: the relative path between 1st and 2nd paths
function relative() {
    local pos="${1%%/}" ref="${2%%/}" down=''

    while :; do
        test "$pos" = '/' && break
        case "$ref" in $pos/*) break;; esac
        down="../$down"
        pos=${pos%/*}
    done

    echo "$down${ref##$pos/}"
}

function moveAndLink()
{
	local symlink=$1
	local destDir=$2
	local name=$3


	[ ! -d $destDir ] && \
		echo "$destDir doest not exist" && return 1

	[ -z $name ] && \
		name=$(basename $symlink)

	local destPath=$destDir/$name

	local symlinkDir=$(dirname $symlink)

	[ ! -d $symlinkDir ] && \
		mkdir -p $symlinkDir

	## Is the $symlink already a link?
	if [ -L $symlink ]; then
		# Is $symlink already pointing to $destPath?
		if [ $symlink -ef $destPath ]; then
			echo "$symlink already linked to $destPath"
			return 0
		else
		# Else, they're point to different places. 
			echo -----------------------------------------
			echo "Moving files from $symlink to $destPath"
			echo -----------------------------------------
			for f in $( ls $symlink ); do
				mv -v $symlink/$f $destPath
			done
			echo -----------------------------------------
			echo "Removing $(readlink $symlink)"
			echo -----------------------------------------
			rmdir -v $(readlink $symlink)
		fi
	elif [ -e $symlink ]; then
		if [ -d $destPath ]; then
			echo -----------------------------------------
			echo "Moving contents ${symlink} to ${destPath}"
			echo -----------------------------------------
			mv -v $symlink/* $destPath
			rmdir -v $symlink
		else
			echo -----------------------------------------
			echo "Moving ${symlink} to ${destPath}"
			echo -----------------------------------------
			mv -v $symlink $destPath
		fi
	fi

	[ ! -d $destPath ] && mkdir -v $destPath

	echo -----------------------------------------
	echo "Creating link from ${symlink} to ${destPath}"
	echo -----------------------------------------
	ln -vsnf $destPath $symlink
}


# Creates a symlink from $linkFile to $sourceFile
# If $linkFile is a directory, that already exists
# Then those existing contents will be copied
#
function relink(){
	local sourceFile=$( dynamicLookup $( deepReadLink $1 ) )
	local linkFile=$2
	local renamedLinkFile="${linkFile}-$(date +%^s)"

	#Is the linkFile a directory that already exists
	#.. and linkFile isn't pointing to the same location to the sourceFile
	if [ -d $linkFile ] && [ ! $linkFile -ef $sourceFile ]; then
		echo -----------------------------------------
		echo "Renaming ${linkFile} to ${renamedLinkFile}"
		echo -----------------------------------------
		#rename it
		mv -v $linkFile $renamedLinkFile
	fi

	#Create the symlinks in $HOME
	ln -vsnf $sourceFile $linkFile; 

	#Move over any existing files
	if [ -d $renamedLinkFile ]; then
		echo -----------------------------------------
		echo "Moving files from ${renamedLinkFile} to ${linkFile}" 
		echo -----------------------------------------
		for existingFile in `ls $renamedLinkFile`; do 
			if [ ! -e $linkFile/$existingFile ]; then
				mv -v $renamedLinkFile/$existingFile $linkFile/
				if [ -d $linkFile/.git ]; then
					grep -q $existingFile $linkFile/.gitignore || echo $existingFile >> $linkFile/.gitignore
				fi

			fi
		done
		rm -vrf $renamedLinkFile
		unset renamedLinkFile
	fi
}


function dynamicLookup()
{
    local dir=$(dirname $1)
    local sourceFile=$(basename $1)
    local prefix=${sourceFile%.*}
    local extension=$([[ "$sourceFile" = *.* ]] && echo ".${sourceFile##*.}" || echo '')
    local os=`uname`

    local osSourceFile=""
    

    if [ -z $extension ]; then
        osSourceFile="${prefix}-${os}"
    else
        osSourceFile="${prefix}-${os}${extension}"
    fi

    if [ -e $dir/$osSourceFile ]; then
        echo $dir/$osSourceFile
    else
        echo $dir/$sourceFile
    fi
}

function apps() {
	for app in $(ls $APPSTORE/.versions/); do
		echo $app
	done
}

function appLink() {
	[ $# -eq 2 ] || {
		echo "$0 <app name> <version>"
		return 1
	}

	app=$1
	version=$2
	appPath=$APPS/$app
	installedApp=$APPSTORE/.versions/$app

	[ -d $installedApp ] || {
		echo "$app isn't installed"
		return 1
	}

	sourceLink=$APPSTORE/$app-$version

	[ -d $sourceLink ] || {
		echo "$sourceLink doesn't exist"
		return 1
	}

	ln -vsnf $sourceLink $appPath
}
