#!/bin/sh

# Less - Syntax Highlighting
# https://ole.michelsen.dk/blog/syntax-highlight-files-macos-terminal-less/
LESSPIPE="$(which src-hilite-lesspipe.sh)"
if [ -d "$LESSPIPE" ]; then
	export LESSOPEN="| ${LESSPIPE} %s"
	export LESS=' -R -X -F '
fi
case $(uname) in
	Darwin)
		if [ ! "$(type -a brew)" ]; then
			echo "You need to install Homebrew"
			exit 1
		fi

		ensureCmd brew "/usr/bin/ruby -e $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

		if [[ ! $(type -a envsubst) ]]; then
			brew install gettext
			exit 1
		fi

	# Install all the GNU-Utils
	for package in coreutils diffutils findutils gawk gnu-indent gnu-sed gnu-tar gnu-which gnutls gnu-getopt grep watch wdiff wget; do
		package_path="/usr/local/opt/${package}/"
		bin_path="${package_path}/libexec/gnubin"
		man_path="${package_path}/libexec/gnuman/"

		if [ ! -e "$package_path" ]; then
			verboseExec "brew install $package"
		fi

		[ -d "${bin_path}" ] && export PATH="${bin_path}:${PATH}"
		[ -d "${man_path}" ] && export MANPATH="${man_path}:${MANPATH}"
	done
	;;
Linux)
	echo ""
	;;
esac
