#!/bin/sh

#CD Args
[ -f /usr/share/doc/cdargs/examples/cdargs-bash.sh ] && source /usr/share/doc/cdargs/examples/cdargs-bash.sh

# Bash Completion
[ -f /usr/share/bash-completion/bash_completion ] && /usr/share/bash-completion/bash_completion

umask 002

# Set commandline input style to emacs
set -o emacs

#When running two bash windows, allow both to write to the history, not one stomping the other
shopt -s histappend

#Remove duplicates from history
export HISTCONTROL="ignoredups"
export HISTIGNORE="&:ls:[bf]g:exit"

#Keep multiline commands as one command in history
shopt -s cmdhist

if [ $DISPLAY ] && ! [ $USER == root ]; then
	# Disable PC Speaker in X
	xset b off
	
	# Disable Terminal PC Speaker
	setterm -blength 0
	
	# Allow terminals from remote/local addresses to connect to this X11 Server
	xhost +localhost
	xhost +local:root
	#xhost +quy.dnsalias.org
fi
