#!/bin/bash

pushd $( dirname $BASH_SOURCE ) > /dev/null # go there the directory of this currently 'sourced' script ( quietly )

source ../common/profile
source bashrc

GIT_PROMPT_ONLY_IN_REPO=0
GIT_PROMPT_FETCH_REMOTE_STATUS=0
GIT_PROMPT_THEME=Solarized
source ./montymagic-bash-git-prompt/gitprompt.sh

source npm-completion
source ng-completion

popd  > /dev/null # go back to working directory ( quietly )
