#!/bin/bash
setOrInstall JENV_HOME \
	"$HOME/.jenv" \
	"git clone https://github.com/gcuisinier/jenv.git $JENV_HOME" 

eval "$(jenv init -)"
JAVA_HOME="$( jenv javahome )"
export JAVA_HOME
export JRE_HOME="${JAVA_HOME}/jre"
export MAVEN_OPTS="-XX:+UseG1GC -XX:MaxHeapFreeRatio=40"

case $(uname) in
	Darwin)
		ensureCmd lf "brew install lf"
		;;
	Linux)
		echo ""
		;;
esac

# LF -- The dopest filemanager
LFCD_HOME="$HOME/.config/lf/"
LFCD="${LFCD_HOME}/lfcd.sh"
if [ -f "$LFCD" ]; then
	source "$LFCD"
fi
