#!/bin/sh

# Set the PAGER program to be 'less'.  The "-i" option is for case-insensitive searching
#export EDITOR="/usr/bin/vim"
#export PAGER="/usr/bin/less -i"
export PAGER="/usr/bin/less -i"
if [ -x /usr/local/bin/nvim ]; then
	export EDITOR="/usr/local/bin/nvim" 
else
	export EDITOR="/usr/bin/vim"
fi


# CVS
export CVSUMASK=002

# To make the French Characters Look Sweet
export LANG=en_US.utf8
export LANGVAR=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

# GITHUB
export GITHUB=git@github.com:quynguyen
