#!/bin/sh

# CVS
export CVSUMASK=002

# To make the French Characters Look Sweet
export LANG=en_US.utf8
export LANGVAR=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

# GITHUB
export GITHUB=git@github.com:quynguyen
