#!/bin/sh

[[ -e `which gls` ]] && alias ls="gls --color=auto"
[[ -e `which lazygit`  ]] && alias lg="lazygit"
[[ -e `which nvim` ]] && alias n="nvim"
alias ll="ls -l"
alias lt="ls -ltr"
alias cb="cdb -b"
alias grep="grep --colour=auto"
[[ -e `which tmuxinator` ]] && alias mux="$( which tmuxinator)"

# December 2016 - Note to Quy
# Important.  Makes sure solarized colors look right when running vim, instead of tmux, instead of Guake.  
# Most Stackoverlfow articles say to run 
#	"tmux -2", 
# Howevver, as explaine by: 
#	http://unix.stackexchange.com/posts/119988/revisions
# tmux -2 doesn't properly give the Terminal full 256 colours.  It just emulates it.  Vim doesn't look nice with this emulation.
alias tmux="TERM=xterm-256color $( which tmux )"

alias xml="xmlstarlet"

#git
alias gs="git status"
alias gitpush='git add -A && git commit -m "Force Commit" && git push'

#Set Linux equivalents for OS's pbcopy and pbpaste, which are commandline tools for pushing and popping stuff into system clipboard.
if [[ `uname` -ne "Darwin" ]]; then
	if [[ `which xsel 2> /dev/null` ]]; then
		alias pbcopy='xsel --clipboard --input'
		alias pbpaste='xsel --clipboard --output'
	elif [[ `which xclip 2> /dev/null` ]]; then
		alias pbcopy='xclip -selection clipboard'
		alias pbpaste='xclip -selection clipboard -o'
	fi
fi
