#!/bin/sh

function pwdp()
{
    cd `xsel -o -b`
}

function pp()
{
    pwdp
}

function getOsSpecificFile()
{
    local dir=$(dirname $1)
    local sourceFile=$(basename $1)
    local prefix=${sourceFile%.*}
    local extension=$([[ "$sourceFile" = *.* ]] && echo ".${sourceFile##*.}" || echo '')
    local os=`uname`

    local osSourceFile=""
    

    if [ -z $extension ]; then
        osSourceFile="${prefix}-${os}"
    else
        osSourceFile="${prefix}-${os}${extension}"
    fi

    if [ -e $dir/$osSourceFile ]; then
        echo $dir/$osSourceFile
    else
        echo $dir/$sourceFile
    fi
}
