#!/bin/sh

function spinw() {
  spin up "$1" \
    --wait --wait-timeout=-1 --wait-for-unit=spin.target \
    "${@:2}"
}

function spinwait() {
  spin up "$1" \
    --name "$2" \
    --config "$1".branch="${3:-main}" \
    --wait --wait-timeout=-1 --wait-for-unit=spin.target
}

function spinbg() {
  spin up ShopifyFRS/bourgeois \
    --name "$1" \
    --wait --wait-timeout=-1 --wait-for-unit=spin.target \
    --config business-platform.branch="${2:-main}" \
}

function spinbp_cap_us() {
  spin up business-platform \
    --name "$1" \
    --wait --wait-timeout=-1 --wait-for-unit=spin.target \
    --config business-platform.branch="${2:-main}" \
    --config shopify.env.SPIN_BUSINESS_PLATFORM_TOPHAT_USNL=1
}

function spinbp_sp_ro() {
  spin up business-platform \
    --name "$1" \
    --wait --wait-timeout=-1 --wait-for-unit=spin.target \
    --config business-platform.branch="${2:-main}" \
    --config shopify.env.SPIN_BUSINESS_PLATFORM_TOPHAT_SP_ROMANIA=1
}

function spinbp_sp_fr() {
  spin up business-platform \
    --name "$1" \
    --wait --wait-timeout=-1 --wait-for-unit=spin.target \
    --config business-platform.branch="${2:-main}" \
    --config shopify.env.SPIN_BUSINESS_PLATFORM_TOPHAT_SP_FRANCE=1

  }

function spinbp_cap_au() {
  spin up ShopifyFRS/bourgeois \
    --name "$1" \
    --wait --wait-timeout=-1 --wait-for-unit=spin.target \
    --config business-platform.branch="${2:-main}" \
    --config shopify.env.SPIN_BUSINESS_PLATFORM_TOPHAT_CAPITAL_AU=1
  }

function spinbp_sp_au() {
  spin up business-platform \
    --name "$1" \
    --wait --wait-timeout=-1 --wait-for-unit=spin.target \
    --config business-platform.branch="${2:-main}" \
    --config shopify.env.SPIN_BUSINESS_PLATFORM_TOPHAT_SP_AU=1
  }

function spinbp_au() {
  spin up ShopifyFRS/bourgeois \
    --name "$1" \
    --wait --wait-timeout=-1 --wait-for-unit=spin.target \
    --config business-platform.branch="${2:-main}" \
    --config shopify.env.SPIN_BUSINESS_PLATFORM_TOPHAT_SP_AU=1
    --config shopify.env.SPIN_BUSINESS_PLATFORM_TOPHAT_CAPITAL_AU=1
  }

